# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\Navigation\UI\navig.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(11)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.param = QtWidgets.QWidget()
        self.param.setObjectName("param")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.param)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.param)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.tableView = QtWidgets.QTableView(self.param)
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setWordWrap(False)
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_2.addWidget(self.tableView)
        self.label_4 = QtWidgets.QLabel(self.param)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.tableView_2 = QtWidgets.QTableView(self.param)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_2.addWidget(self.tableView_2)
        self.frame = QtWidgets.QLabel(self.param)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.tabWidget.addTab(self.param, "")
        self.camera = QtWidgets.QWidget()
        self.camera.setObjectName("camera")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.camera)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.camera)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.camfocus_minus = QtWidgets.QPushButton(self.camera)
        self.camfocus_minus.setObjectName("camfocus_minus")
        self.horizontalLayout_2.addWidget(self.camfocus_minus)
        self.camfocus_plus = QtWidgets.QPushButton(self.camera)
        self.camfocus_plus.setObjectName("camfocus_plus")
        self.horizontalLayout_2.addWidget(self.camfocus_plus)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.camera)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.eposureslider = QtWidgets.QSlider(self.camera)
        self.eposureslider.setOrientation(QtCore.Qt.Horizontal)
        self.eposureslider.setObjectName("eposureslider")
        self.horizontalLayout_3.addWidget(self.eposureslider)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.laser_780 = QtWidgets.QLabel(self.camera)
        self.laser_780.setObjectName("laser_780")
        self.horizontalLayout_4.addWidget(self.laser_780)
        self.laser_850 = QtWidgets.QCheckBox(self.camera)
        self.laser_850.setObjectName("laser_850")
        self.horizontalLayout_4.addWidget(self.laser_850)
        self.checkBox_2 = QtWidgets.QCheckBox(self.camera)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.camera, "")
        self.proj = QtWidgets.QWidget()
        self.proj.setObjectName("proj")
        self.tabWidget.addTab(self.proj, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "Maker"))
        self.label_4.setText(_translate("MainWindow", "Location"))
        self.frame.setText(_translate("MainWindow", "Frame"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.param), _translate("MainWindow", "param"))
        self.label_6.setText(_translate("MainWindow", "Focus"))
        self.camfocus_minus.setText(_translate("MainWindow", "PushButton"))
        self.camfocus_plus.setText(_translate("MainWindow", "PushButton"))
        self.label_7.setText(_translate("MainWindow", "Expo"))
        self.laser_780.setText(_translate("MainWindow", "Laser"))
        self.laser_850.setText(_translate("MainWindow", "850"))
        self.checkBox_2.setText(_translate("MainWindow", "780"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.camera), _translate("MainWindow", "camera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.proj), _translate("MainWindow", "proj"))

